import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import BottomBar from "./components/BottomBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="pb-6 sm:pb-0">{children}</div>
          <footer className="text-center text-xs text-neutral-500 py-8">
            <div className="flex items-center justify-center gap-3">
              <span>© {new Date().getFullYear()} NoMo</span>
              <span>•</span>
              <a className="underline underline-offset-2 hover:opacity-80" href="/privacy">Privacy</a>
              <span>•</span>
              <a className="underline underline-offset-2 hover:opacity-80" href="/terms">Terms</a>
            </div>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
